version: "3.8"
services:
    mysql-db:
      image: mysql
      restart: always

      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: mueblestgo_db
      ports:
        - 33061:3306
    proyecto1_mingeso:
      container_name: app-web-simple
      image: maxahumada/proyecto1_mingeso
      ports:
        - "8090:8090"
      environment:
        - DB_URL=jdbc:mysql://mysql-db:3306/mueblestgo_db
        - DB_USERNAME=root
        - DB_PASSWORD=123456
      deploy:
        restart_policy:
          condition: on-failure
      depends_on:
        - mysql-db
